ContactApp/urls.py
from django.urls import path, include, re_path
from .views import ContactPage

urlpatterns = [
    path('', ContactPage, name="contact-page"),
]

VotingApp/urls.py
from django.urls import path
from . import views 

urlpatterns = [
    path('', views.home, name="home"),
    path('polls/<id>/', views.VoteView, name="pols"),
    path('dashboard/', views.PanelView, name='dashboard'),
    #If changing this alseo change LOGIN_REDIRECT_URL in settings
    path('dashboard/titles/<id>/', views.TitlesView, name='titles'),
    path('dashboard/delete/<id>/', views.DeleteTitle, name='delete'),
    path('dashboard/edit/<id>/', views.EditOption, name='edit'),
    path('dashboard/option/delete/<id>/', views.DeleteOption, name='deleteOption'),
    path('dashboard/titles/edit/<id>/', views.TitleEdit, name='titleEdit'),
]

VotingRoot/urls.py
from django.urls import path, include, re_path
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.views.static import serve
from django.utils.translation import  gettext_lazy
from VotingApp.views import tester

#Changing some values on admin page
admin.site.site_title = gettext_lazy("Let's Vote")
admin.site.site_header = gettext_lazy("Let's Vote")
admin.site.index_title = gettext_lazy("Let's Vote")

#to use other template for admin
# admin.site.index_template = 'index.html'
# admin.autodiscover()

#To Customise error 404, 500, 403, 400 
#look https://docs.djangoproject.com/en/2.1/topics/http/views/#customizing-error-views

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('test/<id>/', tester, name='0'),

    path('',include('VotingApp.urls')),
    path('account/',include('AccountsApp.urls')),
    path('contact/',include('ContactApp.urls')),

    re_path(r'media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    re_path(r'static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
]

ContactApp/models.py
from django.db import models

# Create your models here.
class ContactModel(models.Model):
	email = models.EmailField()
	message = models.TextField()

	def __str__(self):
		return self.email

ContactApp/forms.py
from .models import ContactModel
from django import forms

class ContactForm(forms.ModelForm):
	class Meta:
		model = ContactModel
		exclude = []

ContactApp/views.py
from django.shortcuts import render, redirect
from .forms import ContactForm
from django.contrib import messages
from django.urls import reverse

def ContactPage(request):
	form = ContactForm()
	data = {'form':form,'title':'Contact us'}
	if request.method == "POST":
		form = ContactForm(request.POST)
		if form.is_valid():
			form.save()
			return render(request,'ContactApp/done.html', data)
		else:
			print(form)
			error = "The action failed "
			data.update({'error':error})


	return render(request,'ContactApp/contact.html',data)

Container/templates/ContactApp/contact.html
{%extends 'header.html'%}

{%block content%}
<center>
    <div class="card" style="background-color: #000;border-radius: 17px;padding: 20px;margin: 5%">
        <!-- <h1 style="color: #fff" class="title">Contact us</h1> -->
        <br>
        {% include 'components/form.html' %}


{% load crispy_forms_tags %}
<style type="text/css">
    #id_email{width: 100%;min-height:20px;border-radius: 5px;font-size: 20px;padding: 5px 7px;margin-bottom: 14px}

    #id_message{width: 100%;min-height:20px;border-radius: 5px;font-size: 20px}
</style>

<form method="post" >
{%csrf_token%}
{{form|crispy}}
<br>
<button type="submit" class="button is-info">submit</button>
</form>
    </div>
</center>
<br><br> 
{%endblock%}

Container/templates/ContactApp/done.html
{%extends 'header.html'%}

{%block content%}
<center>
    <div class="card" style="background-color: #000;border-radius: 17px;padding: 20px;margin: 5%">
        <!-- <h1 style="color: #fff" class="title">Thank You</h1> -->
        <br>
<h1 style="color: #fff">Thank You for You'r feed back</h1>
<br><br> 
    
    </div>
</center>
<br><br> 

{%endblock%}